development:
  clients:
    default:
      # database: yiliao_development
      database: yiliao_production
      hosts:
        # - localhost:27017
        - 61.153.100.122:27017
      options:
        max_pool_size: 25
        connect_timeout: 30
        wait_queue_timeout: 10
  options:
production:
  clients:
    default:
      database: yiliao_production
      hosts:
        - localhost:27017
      options:
        options:
        max_pool_size: 25
        connect_timeout: 30
        wait_queue_timeout: 10
        user: 'kevin'

        # # db.auth("myUserAdmin", "abc123" )
        # # # The password of the user for authentication.
        password: 'sq81816225'

        # # The user's database roles.
        roles:
          -
            role: 'readWrite'
            db:   'yiliao_production'

        # # Change the default authentication mechanism. Valid options are: :scram,
        # # :mongodb_cr, :mongodb_x509, and :plain. (default on 3.0 is :scram, default
        # # on 2.4 and 2.6 is :plain)
        # # auth_mech: :scram

        # # The database or source to authenticate the user against. (default: admin)
        auth_source: 'yiliao_production'
  options: