development:
  clients:
    default:
      database: yiliaohj_development
      hosts:
        - localhost:27017
      options:
        max_pool_size: 25
        connect_timeout: 30
        wait_queue_timeout: 10
  options:
production:
  clients:
    default:
      database: yiliaohj_production
      hosts:
        - localhost:27017
      options:
        options:
        max_pool_size: 25
        connect_timeout: 30
        wait_queue_timeout: 10
  options: