development:
  clients:
    default:
      # database: yiliao_development
      database: yiliao_production
      hosts:
        # - localhost:27017
        - 61.153.100.122:27017
      options:
        max_pool_size: 25
        connect_timeout: 30
        wait_queue_timeout: 10
  options:
production:
  clients:
    default:
      database: yiliao_production
      hosts:
        # - 10.4.44.137:27017
        - localhost:27017
      options:
        options:
        max_pool_size: 25
        connect_timeout: 30
        wait_queue_timeout: 10
        user: 'guyifeng'
        password: 'password'
        roles:
          -
            role: 'readWrite'
            db:   'yiliao_production'
        auth_source: 'yiliao_production'
  options: