development:
  clients:
    default:
      database: yiliao_production
      hosts:
        - 61.153.100.122:27017
      options:
        max_pool_size: 25
        connect_timeout: 30
        wait_queue_timeout: 10
  options:
production:
  clients:
    default:
      database: yiliao_production
      hosts:
        - localhost:27017
      options:
        options:
        max_pool_size: 25
        connect_timeout: 30
        wait_queue_timeout: 10
  options: