# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: edc48cef9f9104b01f7b813d5b3ebb74561bd95cbee26fa94feef11f1365beae3c059482f822628498e7c3d274ef9142b76f07d502e662b75faf57bc5108be74

test:
  secret_key_base: f4de565ae01e9c1edccfde1686e73251492624c5ca640b61856ab5f42ad3dbcdf6ac3c0fb2720e5e688a21a9e2e79c3096d0ee1d21cf29dc9239f41862aef080

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
