:pidfile: ./tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log
development:
  :concurrency: 1
  :queues:
  - [development_sms, 10]
production:
  :concurrency: 1
  :daemon: true
  :queues:
  - [production_sms, 10]